My finished project, week 3, business site
Technigo/project-business-site pull request #106
Opened 2021-01-29 12:06 UTC by matildasvensson85

2021-02-04 09:41 UTC, HIPPIEKICK commented
Hi! Can you submit a link to your netlify? :)

2021-02-04 09:46 UTC, matildasvensson85 commented
> Hi! Can you submit a link to your netlify? :)

Here is the link: https://focused-swirles-cdfc67.netlify.app/

2021-02-04 10:31 UTC, HIPPIEKICK requested changes
Well done Matilda! My main comment is fixing the radio buttons so that only one is clickable at a time. There's a section about it in the [general feedback document](https://www.notion.so/technigo/Week-3-Business-site-9f3ef7b1c0ee480c8a10b9c7e460c475), so check that out as well as the [code guidelines](https://www.notion.so/technigo/Guidelines-for-how-to-write-good-code-69ffb59eac4e4358a7c5752efb873c4e) if you want to recap indentation and conventions.

2021-02-04 10:31 UTC, HIPPIEKICK commented on code/index.html
> +      <h2 class="h2-headline">Log in here</h2>
Try to come up with as descriptive class names as you can. Maybe just headline is enough here? 😇

2021-02-04 10:31 UTC, HIPPIEKICK commented on code/index.html
> +        </label>
You need to give the radio buttons the `name` attribute and give them the same value in order for them to work as a radio button group

2021-02-04 10:31 UTC, HIPPIEKICK commented on code/script.js
> +document.getElementById("question-2").onclick = toggle
Nice and clean!

2021-02-04 10:31 UTC, HIPPIEKICK commented on code/script.js
> +const answer2 = document.getElementById('answer-2');
These are not used

2021-02-04 10:31 UTC, HIPPIEKICK commented on code/style.css
> +.body {
Remove the `.` to style the body element

2021-02-04 10:31 UTC, HIPPIEKICK commented on code/style.css
> +}
Nice! Just remember the indentation

2021-05-31 05:05 UTC, KarolCislowski commented
Hello, it's your project. Do you remember me? I may be imperfect, but I believe you can still change that before you sit down to your final masterpiece!
![image](https://user-images.githubusercontent.com/50926159/120141019-f9ed2900-c1db-11eb-95df-db20da4f1088.png)

2021-06-04 10:17 UTC, matildasvensson85 commented
I made the changes, the updated Netlify page can be found here: project-business-website.netlify.app

2021-06-12 12:03 UTC, KarolCislowski approved these changes
good job 👍🏻

2021-08-10 12:04 UTC, closed without merging