Business Site - Laima
Technigo/project-business-site pull request #108
Opened 2021-01-29 13:38 UTC by leelalaim

2021-02-04 10:49 UTC, HIPPIEKICK requested changes
Good job Laima! I would just like to ask you to fix the comments I made about the `label`s. They are important for accessibility reasons, and the `for` - `id` is necessary for the connection to be made (you can see in your HTTPbin response that the checkbox and the radio button info is not there right now). Read more about this in the [general feedback document](https://www.notion.so/technigo/Week-3-Business-site-9f3ef7b1c0ee480c8a10b9c7e460c475).

2021-02-04 10:49 UTC, HIPPIEKICK commented on README.md
> +One of the tasks hat was aimed to be achieved - adding an icon after the title in the accordion, indicating whether the section is expanded or collapsed. After trying out different ways of achieving
Great!

2021-02-04 10:49 UTC, HIPPIEKICK commented on code/index.html
> +    <form class="form" action="https://httpbin.org/anything" method="POST">
[Here](https://www.w3schools.com/tags/tag_label.asp) you can read about why we should add `<label>`s to our inputs

2021-02-04 10:49 UTC, HIPPIEKICK commented on code/index.html
> +          <label for="contactChoice2">Phone</label>
The `for` and `id` attributes need to correspond

2021-02-04 10:49 UTC, HIPPIEKICK commented on code/index.html
> +        </label>
These should also have `for` and `id` attributes

2021-02-04 10:49 UTC, HIPPIEKICK commented on code/script.js
> +document.getElementById("section4").onclick = toggle;
If you decide to go with semicolons, you should have them everywhere (so add them to the function as well). Apart from that, nice and clean!

2021-02-04 10:49 UTC, HIPPIEKICK commented on code/style.css
> +}
Really nice!

2021-02-05 14:37 UTC, leelalaim commented
Made the changes.

2021-08-10 12:04 UTC, closed without merging