Business site - Andrea
Technigo/project-business-site pull request #109
Opened 2021-01-29 14:22 UTC by Andrealarsson

Here is my business site for my own  travel agency.

2021-02-04 12:03 UTC, EmOlsz requested changes
Great job Andrea!
Your project is well structured and consequent. There are only some small things to fix - take a look at my comments and provide changes.
Moreover, take a look at the [general feedback document](https://www.notion.so/technigo/Week-3-Business-site-9f3ef7b1c0ee480c8a10b9c7e460c475)

2021-02-04 12:03 UTC, EmOlsz commented on code/index.html
> +      <div class="accordion">
Well designed structure - good job :)

2021-02-04 12:03 UTC, EmOlsz commented on code/script.js
> +
We don't need to add so many empty lines - one is completely enough. Let's fix that

2021-02-04 12:03 UTC, EmOlsz commented on code/style.css
> +ul {
Remember - we shouldn't style by anything else than CSS classes. Let's add classes in HTML and style them over here

2021-02-04 12:03 UTC, EmOlsz commented on code/style.css
> +  cursor: pointer;
Great you remembered about `pointer` value!

2021-02-15 20:40 UTC, Andrealarsson commented
Changes done! :)

2021-02-16 10:48 UTC, EmOlsz commented
Thank you, project approved :)

2021-02-16 10:48 UTC, EmOlsz approved these changes

2021-08-10 12:04 UTC, closed without merging