Project 3 - Isabella Billgren
Technigo/project-business-site pull request #111
Opened 2021-01-29 16:46 UTC by Bellsibub

Completed all BLUE, RED and BLACK requirements.
(see readme for more info)

2021-02-04 12:55 UTC, EmOlsz requested changes
Wow Isabella, congrats! ⭐️ Very nice, well done project. I'm impressed by your BEM implementation, custom input styles and JS logic. There are only super small things that needs to be fixed before approval, check them out :)
Moreover, feel free to analyse [Week 3 Master document](https://www.notion.so/technigo/Week-3-Business-site-9f3ef7b1c0ee480c8a10b9c7e460c475)

2021-02-04 12:55 UTC, EmOlsz commented on code/index.html
> +    <link rel="stylesheet" href="main.css" />
Next time let's remember about `./` in path to file ;)

2021-02-04 12:55 UTC, EmOlsz commented on code/index.html
> +      <video class="hero__video" playsinline autoplay muted loop>
Great job with BEM methodology!

2021-02-04 12:55 UTC, EmOlsz commented on code/index.html
> +        Let the <br />
We shouldn't use `<br />` tags - more information on that in [Week 2 Master document](https://www.notion.so/technigo/Week-2-Project-news-site-bbe695289d154ff98d6a247cef873f07)

2021-02-04 12:55 UTC, EmOlsz commented on code/index.html
> +            <label class="form__input-wrapper" for="name">
If we decide to nest input inside label, then we don't need to add for - id pair. More details in Week 3 Master document

2021-02-04 12:55 UTC, EmOlsz commented on code/index.html
> +    <section class="accordion">
Great accordion structure :)

2021-02-04 12:55 UTC, EmOlsz commented on code/script.js
> +accordion.addEventListener("click", (event) => {
Very complex logic, I'm impressed!

2021-02-04 12:55 UTC, EmOlsz commented on code/styles/forms.css
> +.form__input-radio:checked::before {
👍

2021-02-04 12:55 UTC, EmOlsz commented on code/styles/forms.css
> +label.form__input-wrapper--submit-section {
Would be better to add separate class for `label`, let's remember about this next time!

2021-02-04 12:55 UTC, EmOlsz commented on code/styles/gridLayout.css
> +*/
All commented code should be removed before final push - let's fix this

2021-02-07 10:19 UTC, Bellsibub commented
Requested changes have been pushed :)

2021-02-08 12:05 UTC, EmOlsz approved these changes

2021-08-10 12:04 UTC, closed without merging