Persson Tine Project-business site
Technigo/project-business-site pull request #123
Opened 2021-01-30 22:28 UTC by gtine

2021-01-31 12:28 UTC, gtine commented
Creating a new since some stuff got lost in last version.

2021-02-04 17:24 UTC, HIPPIEKICK requested changes
Hi Tine! Some small changes need to be done to this project. Take a look at my comments and the [general feedback document](https://www.notion.so/technigo/Week-3-Business-site-9f3ef7b1c0ee480c8a10b9c7e460c475) for more tips.

2021-02-04 17:24 UTC, HIPPIEKICK commented on code/index.html
> +    </div>
Check indentation! And there should be no space between = and value:
`<p class="content1" id="content1">`

2021-02-04 17:24 UTC, HIPPIEKICK commented on code/index.html
> +      <input name="Number" type="Phone-number" placeholder="Phone-number">
Don't forget the labels!

2021-02-04 17:24 UTC, HIPPIEKICK commented on code/index.html
> +    </div>
Label 👀

2021-02-04 17:24 UTC, HIPPIEKICK commented on code/index.html
> +      <input type="radio" >
Radio buttons need the `name` attribute in order to work together as a group. Read more in the general feedback document. Also, when you have the label outside of the input, you need to add a corresponding `id` to the input

2021-02-04 17:24 UTC, HIPPIEKICK commented on code/style.css
> +}
Nice!

2021-02-04 17:24 UTC, HIPPIEKICK commented on code/style.css
> +  transform: rotate(90deg);
Looks like this is making your content to wide (i.e. not responsive):
<img width="417" alt="Skärmavbild 2021-02-04 kl  18 14 32" src="https://user-images.githubusercontent.com/51529201/106929748-09b89d00-6715-11eb-92e3-02489eb51140.png">

2021-02-04 17:24 UTC, HIPPIEKICK commented on code/style.css
> +.content1, .content2, .content3, .content4 {
Maybe they can have the same class name? :)

2021-02-04 17:24 UTC, HIPPIEKICK commented on code/style.css
> +
One empty line is enough ;)

2021-02-10 22:00 UTC, gtine commented
I have made all the changes that was requested. Ive had some trouble understanding hos to add changes in the right file but I hope Ive done it the right way now (first cloning my file then pushing back (not to origin master)? Please let me know otherwise or if there is another way. Thanks for your feedback! Tine

2021-02-22 14:49 UTC, closed without merging