project-business-site
Technigo/project-business-site pull request #132
Opened 2021-01-31 16:00 UTC by Irina-web-dev

During this project I have used learnings from the previous project. I feel quite good about the box-model approach and flexbox.
 
I don´t quite like how responsiveness works in this project. Maybe I can have feedback on that, what could have been done differently? With mobile first approach it was easier and I will try to stick with this approach for the next projects.

Looking forward receiving your code review.

2021-02-05 16:03 UTC, HIPPIEKICK requested changes
Hi Irina! I really like your design although some small responsiveness-bugs sneaked in. Please have a look at that before approval. Also, take a look at the [general feedback document](https://www.notion.so/technigo/Week-3-Business-site-9f3ef7b1c0ee480c8a10b9c7e460c475) for this week to get more tips :) Have a nice weekend!

2021-03-22 00:15 UTC, Irina-web-dev commented
> Hi Irina! I really like your design although some small responsiveness-bugs sneaked in. Please have a look at that before approval. Also, take a look at the [general feedback document](https://www.notion.so/technigo/Week-3-Business-site-9f3ef7b1c0ee480c8a10b9c7e460c475) for this week to get more tips :) Have a nice weekend!

2021-03-22 00:18 UTC, Irina-web-dev commented on code/script.js
> +});
Hi @HIPPIEKICK ,

Thank you for your code review and feedback.
I made the changes and I also changed the structure of styling to mobile first approach, it seemed much more convenient.

2021-04-14 07:51 UTC, HIPPIEKICK approved these changes

2021-08-10 12:04 UTC, closed without merging