Project 3
Technigo/project-business-site pull request #137
Opened 2021-01-31 18:35 UTC by Pauan8

2021-02-05 17:44 UTC, EmOlsz requested changes
Very impressive project Pauline, congratulations :)
There are some minor changes I would like you to apply, take a look at my comments.
Moreover, feel free to check out [Week 3 Master document!](https://www.notion.so/technigo/Week-3-Business-site-9f3ef7b1c0ee480c8a10b9c7e460c475)

2021-02-05 17:44 UTC, EmOlsz commented on code/index.html
> +  <link rel="stylesheet" href="style.css">
Let's remember about `./` in path to file ;)

2021-02-05 17:44 UTC, EmOlsz commented on code/index.html
> +  <header class="header">
Impressive BEM methodology implementation!

2021-02-05 17:44 UTC, EmOlsz commented on code/index.html
> +      <div class="nav-wrapper__button"> <img src="./images/menu.png"></div>
We could improve this indentations :

```
<div class="nav-wrapper__button">
  <img src="./images/menu.png">
</div>
```

2021-02-05 17:44 UTC, EmOlsz commented on code/index.html
> +          <fieldset class="signup-inner__form__fieldset" class="sigup__fieldset" class="sipgnup__field">
Hmm, if you need to add multiple amount of classes, you should just divide them by whitespace, not create new `class` attribute :

```
<fieldset class="signup-inner__form__fieldset sigup__fieldset sipgnup__field">
```

Needs to be fixed

2021-02-05 17:44 UTC, EmOlsz commented on code/index.html
> +          <div><label for="privacy" class="signup-inner__form__check"><input class="signup-inner__form__input"
There is a lot of wrong indentations, let's fix them all

2021-02-05 17:44 UTC, EmOlsz commented on code/index.html
> +        <source media="(max-width: 600px) and (max-device-width: 600px)" srcset="./images/colors350px.jpg">
We don't have to specify both `max-width` and `max-device-width` - the first one is completely enough :)

2021-02-05 17:44 UTC, EmOlsz commented on code/index.html
> +        <div class="footer-wrapper__social__icon"><img src="./images/Fb.svg"></div>
Indentations over here as well.
Moreover, both file names and directory names should be lowercase, so instead of `Fb.svg` we should name it `fb.svg`

2021-02-05 17:44 UTC, EmOlsz commented on code/index.html
> +  <script src="script.js"></script>
`./`

2021-02-05 17:44 UTC, EmOlsz commented on code/script.js
> +function accordionExpand(acc, i) {
Impressive, great job!

2021-02-05 17:44 UTC, EmOlsz commented on code/style.css
> +  cursor: url(./images/cursor.png) 1 1, pointer;
Made my day, you should be really proud achieving this!

2021-02-05 17:44 UTC, EmOlsz commented on code/style.css
> +  animation-timing-function: linear;
Or we could use shorthand :

```
animation: slidedown linear infinite
```

2021-02-05 17:44 UTC, EmOlsz commented on code/style.css
> +  overflow-x: hidden;
Or just `overflow: hidden`

2021-02-05 17:44 UTC, EmOlsz commented on code/style.css
> +  ;
Ups, let's delete this ;)

2021-02-05 17:44 UTC, EmOlsz commented on code/style.css
> +::placeholder {
I think you wanted to write 

```
input::placeholder
```

2021-02-05 22:01 UTC, Pauan8 commented
Done changes after your great comments :)

2021-02-08 11:32 UTC, EmOlsz approved these changes

2021-08-10 12:04 UTC, closed without merging