Project Business Site - By Linnéa Helén
Technigo/project-business-site pull request #151
Opened 2021-01-31 22:04 UTC by Polkapetunian

I went for the blue goals and one red (putting icons on the accordion)

2021-02-09 09:27 UTC, EmOlsz requested changes
Hello Linnéa! Very nice project, great job :)
Some minor things needs to be fixed though, take a look at my comments for more details.
Moreover, feel free to check out [Week 3 Master document](https://www.notion.so/technigo/Week-3-Business-site-9f3ef7b1c0ee480c8a10b9c7e460c475)

2021-02-09 09:27 UTC, EmOlsz commented on code/index.html
> +    <link rel="stylesheet" href="./style.css ">
Thank you for remembering about `./` in path to file :)

2021-02-09 09:27 UTC, EmOlsz commented on code/index.html
> +      <picture>
Well done hero image!

2021-02-09 09:27 UTC, EmOlsz commented on code/index.html
> +      <br>
We shouldn't use `<br />` tags, they are deprecated. Their main features is that they break the line, but you don't need it over here, `<h3 />` tag is doing that anyway. Let's delete this `<br />`

2021-02-09 09:27 UTC, EmOlsz commented on code/index.html
> +        <input type="radio" name="date" value="Sat 17th Apr 2021">
Well done connection between `<label />` and `<input />`!

2021-02-09 09:27 UTC, EmOlsz commented on code/index.html
> +          Unsplash</a></span></p>
Ups, very weird code formatting. Let's fix this

2021-02-09 09:27 UTC, EmOlsz commented on code/style.css
> +  margin: 15px 0 15px 0;
We can simplify this property :

```
margin: 15px 0;
```

2021-02-09 09:27 UTC, EmOlsz commented on code/style.css
> +  height: 0px;
No need to specify unit if value is equal 0 :

```
height: 0;
```

2021-02-09 09:27 UTC, EmOlsz commented on code/style.css
> +  padding: 0 10px 0 10px;
```
padding: 0 10px;
```

2021-02-09 09:27 UTC, EmOlsz commented on code/style.css
> +margin: 60px 0 30px 0;
Ups, wrong indentations

2021-02-09 09:27 UTC, EmOlsz commented on code/style.css
> +  "footer footer";
Hmm, I think you don't need this ;)

2021-03-04 09:23 UTC, EmOlsz commented
Thank you for fixing `<br />` tags Linnea :) I will be waiting for other changes, after seeing them I will accept whole project!

2021-04-18 19:49 UTC, Polkapetunian commented
I have fixed the remaining issues. =)

2021-04-19 11:17 UTC, EmOlsz approved these changes

2021-08-10 12:04 UTC, closed without merging