Tobias Hagberg, Jan2021 -Team Tigers
Technigo/project-business-site pull request #158
Opened 2021-02-01 10:46 UTC by TobiasHagberg

Tobias Hagberg, Jan2021 -Team Tigers

2021-02-09 16:23 UTC, HIPPIEKICK requested changes
Hi Tobias! Please have a look at my comments in your HTML file regarding the different tags, as well as the responsiveness of your page. Take a look at the [code guidelines](https://www.notion.so/technigo/Guidelines-for-how-to-write-good-code-69ffb59eac4e4358a7c5752efb873c4e) if you want to recap conventions. Check out the [general feedback document](https://www.notion.so/technigo/Week-3-Business-site-9f3ef7b1c0ee480c8a10b9c7e460c475) for project-specific tips.

2021-02-09 16:23 UTC, HIPPIEKICK commented on code/script.js
> +})
Use semicolons either everywhere or not at all

2021-02-09 16:23 UTC, HIPPIEKICK commented on code/style.css
> +  width: 100%;
These two together makes the content grow too wide:
<img width="357" alt="Skärmavbild 2021-02-09 kl  17 13 03" src="https://user-images.githubusercontent.com/51529201/107392539-13b61380-6afa-11eb-9a9e-2bd91c26d2e9.png">

2021-05-31 04:55 UTC, KarolCislowski commented
Hello, it's your project. Do you remember me? I may be imperfect, but I believe you can still change that before you sit down to your final masterpiece!
![image](https://user-images.githubusercontent.com/50926159/120141019-f9ed2900-c1db-11eb-95df-db20da4f1088.png)

2021-06-29 08:38 UTC, TobiasHagberg commented
Hi Matilda and Karol,
Changes has been made to this weeks project and lesson learned! :)

Kind regards
Tobias

2021-07-04 15:41 UTC, KarolCislowski approved these changes
Nice page 🎉

2021-08-10 12:04 UTC, closed without merging