Anna Lenksjö Business Siter
Technigo/project-business-site pull request #161
Opened 2021-02-01 18:53 UTC by annalenksjo

2021-02-09 17:05 UTC, HIPPIEKICK requested changes
Hi Anna! Let's clean up a bit by fixing the indentation and removing unused code and console.logs :) Check out the [general feedback document](https://www.notion.so/technigo/Week-3-Business-site-9f3ef7b1c0ee480c8a10b9c7e460c475) for project specific tips!

2021-02-09 17:05 UTC, HIPPIEKICK commented on code/index.html
> +         <p id ="accordionContent" class="answer"> We are a small business, located in the Nordics.</p>
Remove the space before the `=` :)

2021-02-09 17:05 UTC, HIPPIEKICK commented on code/script.js
> +let accordionContentThree = document.getElementById("accordionContentThree")
These can be declared with `const` becasue the values are not changing. Also, be consistent in whether you're using semicolons or not

2021-02-09 17:05 UTC, HIPPIEKICK commented on code/script.js
> +console.log(accordionHeaderTwo);
Remove console.logs before production

2021-02-09 17:05 UTC, HIPPIEKICK commented on code/script.js
> +    })
Remove indentation here :)

2021-02-09 17:05 UTC, HIPPIEKICK commented on code/style.css
> +  }
A little too wide content in tablet:
<img width="638" alt="Skärmavbild 2021-02-09 kl  18 03 37" src="https://user-images.githubusercontent.com/51529201/107399560-241dbc80-6b01-11eb-9c61-6f5e9daae939.png">

2021-02-25 08:21 UTC, annalenksjo commented
I have corrected most of the comments. I hope it is okay now :-) I have not implemented for example the main-section but I will take those comments with me for future projects.

2021-03-18 15:00 UTC, annalenksjo commented
I have corrected the project so I hope it can be approved now.

2021-04-14 07:39 UTC, HIPPIEKICK approved these changes

2021-08-10 12:04 UTC, closed without merging