Drag Doll, Hannah Jesinkey
Technigo/project-business-site pull request #163
Opened 2021-02-10 10:28 UTC by jesinkey

Sorry for the delay! Didn't realise I had missed this. Poyan said it was OK.
/ Hannah

2021-02-16 13:29 UTC, HIPPIEKICK requested changes
Hi Hannah!
Some pointers below:
**HTML**
- Instead of writing the`value` for the inputs which will force the user to delete what you've written, you could look into `placeholder`
- Attribute's values needs quotation marks, e.g. `id="fname"` instead of `id=fname`
- Check indentation, and make sure the tags correspond -> `<h3></h3>`
- From requirements: Site should have a signup form with _at least three different input types_

**JS**
- Remove console.logs
- Be consistent whether you're using semicolons or not
- The toggle function that was already declared is reusable thanks to the `this` keyword. You don't have to change it, it's just good to be aware of :)

**CSS**
- It's responsive and the accordion looks super - so no changes required!

2021-02-16 20:07 UTC, jesinkey commented
Hi! Updated according to the above and pushed to GIT :)

2021-02-22 15:09 UTC, HIPPIEKICK commented on code/index.html
> +                    <li><a href='/Q&A/'>Q&A</a>
These are siblings and should have the same level of indentation :)

2021-02-22 15:10 UTC, HIPPIEKICK approved these changes

2021-08-10 12:04 UTC, closed without merging