business site
Technigo/project-business-site pull request #71
Opened 2020-09-05 13:36 UTC by destinyleia

Hi,

Finally my github worked so here is my first project! :D 

My first project will do a comeback when you "minst anar det"! 

Thanks & hope u like it!

2020-09-11 15:20 UTC, bealun requested changes
Hey! To be able to review your code I do need a link to your deployed website 👋 
Please update you README with info on your project and a link to your site.

2020-09-12 11:31 UTC, destinyleia commented
Hi, I have updated the readme now, sorry I forgot about that part! :D


Den fre 11 sep. 2020 kl 17:20 skrev Beatrice Lundevall <
notifications@github.com>:

> *@bealun* requested changes on this pull request.
>
> Hey! To be able to review your code I do need a link to your deployed
> website 👋
> Please update you README with info on your project and a link to your site.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Technigo/project-business-site/pull/71#pullrequestreview-486901512>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APBAA2CZIBZGBVQ4LYSIU7TSFI54DANCNFSM4Q25E64Q>
> .
>

2020-09-12 11:32 UTC, destinyleia commented
Hi, Sorry totally missed that part! Now it's updated! :D

2020-09-12 13:49 UTC, bealun approved these changes
Such a nice project you've built 🌟 You've got some great code structure which is really important so keep this up! I wanna encourage you to push your code more frequently, like 3 to 4 times a day, and with informative commit messages - that's how we work in tech so make it a habit. 
I've left some comments with feedback and you've done a great job with the hover effects and a lot of cool CSS styling. Be super proud of yourself!! 🎉

2020-09-12 13:49 UTC, bealun commented on index.html
> +    <link rel="stylesheet" href="./style.css">
For next week I wanna see a favicon here 😎

2020-09-12 13:49 UTC, bealun commented on index.html
> +</div>
Nice structure and indentation - keep it up!

2020-09-12 13:49 UTC, bealun commented on index.html
> +</html>
A small footer would have been nice but it's okey for now!

2020-09-12 13:49 UTC, bealun commented on style.css
> +  font-family: Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif;
If you want to use the same font on most places on your site, you can add the font-family in the body styling instead - since it wraps all content!

2020-09-12 13:49 UTC, bealun commented on style.css
> +    content: "\002B";
Perfect use of the 'content' property 🙌

2020-09-12 13:49 UTC, bealun commented on style.css
> +
Good job! If you want a smoother transition you can always check the Inspector tool in your browser to see where the transition should be, also some reading here:
http://css3.bradshawenterprises.com/accordions/

2020-09-12 13:49 UTC, bealun commented on style.css
> +}
Really nice styling features 🚀

2020-09-12 13:49 UTC, bealun commented on style.css
> +  right: 0;
BRAVO!! 🌟

2021-01-13 16:40 UTC, closed without merging